# -*- coding: utf-8 -*-
"""NoisyChordSequenceDenoising.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qc-x1eO7Stp_q67ojuWj2XJk2RmthFaN

# Noisy Chord Sequence Denoising
Sai Dore and Kiran Dsouza

## Imports and Dataset Download
"""

!pip install torch_geometric
import kagglehub
import os
import re
import glob
import json
from dataclasses import dataclass
from typing import List, Tuple, Dict, Optional
import numpy as np
from collections import Counter
import random
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import SAGEConv
import matplotlib.pyplot as plt

path = kagglehub.dataset_download("jacobvs/mcgill-billboard")
print(path)
DATASET_DIR = path

"""## Pipeline: Chord/Beat Processing and Noise Utilities"""

# Pipeline for Colab (McGill Billboard via kagglehub)
# - Loads chord segment annotations
# - (If available) loads beat times and discretizes to beat-level labels
# - Maps chord symbols -> 25 classes (12 roots x {maj/min} + "N")
# - Splits by song into train/val/test
# - Provides uniform-flip and burst-noise corruption utilities
def set_seed(seed: int = 42) -> None:
    random.seed(seed)              # Python RNG seed
    np.random.seed(seed)           # NumPy RNG seed

# Label mapping (25 classes)
# 12 pitch classes in a canonical order
PITCHES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
FLAT_TO_SHARP = {
    "Db": "C#",
    "Eb": "D#",
    "Gb": "F#",
    "Ab": "G#",
    "Bb": "A#",
    "Cb": "B",
    "Fb": "E",
} # Flat -> sharp normalization map
ROOT_RE = re.compile(r"^([A-G](?:#|b)?)")  # Root extraction regex (handles C, C#, Db, etc.)

def normalize_root(root: str) -> Optional[str]:
    root = root.strip()
    root = FLAT_TO_SHARP.get(root, root)   # Convert flats to sharps
    return root if root in PITCHES else None  # Validate root

def chord_to_25class(chord: str) -> int:
    """
    Map a chord label string to:
      0..11  -> root major
      12..23 -> root minor
      24     -> N (no chord / silence / unknown)
    Notes:
    - We keep ONLY root + (maj/min)
    - Everything else is collapsed into maj/min if possible, else N
    """
    s = chord.strip()
    if s in {"N", "X", "NoChord", "no_chord", "NONE"}:     # Common no-chord tokens
        return 24
    # Some Billboard chord files use formats like "C:maj", "C:min", "C", "C:min7", etc.
    m = ROOT_RE.match(s)   # Extract root token
    if not m:
        return 24
    root_raw = m.group(1)    # Root token (e.g., Db)
    root = normalize_root(root_raw)    # Normalize to sharp if flat
    if root is None:
        return 24
    root_idx = PITCHES.index(root)                          # 0..11 pitch class

    # Decide quality (maj/min)
    s_lower = s.lower()
    is_minor = ("min" in s_lower) and ("maj" not in s_lower)

    # Treat "m" (e.g., "Am") as minor only when safe (avoid "maj")
    if not is_minor:
        # Handle cases like "Am" or "A:m" if present
        if re.search(r"(^|[:\s])m($|[^a-z])", s_lower) and ("maj" not in s_lower):
            is_minor = True

    return (12 + root_idx) if is_minor else root_idx        # Encode maj/min

# ----------------------------
# File discovery utilities
# ----------------------------
def list_all_files(root_dir: str) -> List[str]:
    files = []
    for base, _, fnames in os.walk(root_dir):  # Scan all subdirs
        for f in fnames:
            files.append(os.path.join(base, f))   # Add full path
    return files

def find_annotation_files(dataset_dir: str) -> Dict[str, List[str]]:
    """
    Tries to find likely chord/beat annotation files by extension and name.
    Returns dict with keys like 'lab', 'beats', 'json', etc.
    """
    all_files = list_all_files(dataset_dir)    # Get all paths
    buckets = {"lab": [], "beats": [], "chords_json": [], "metadata": []}  # Group paths

    for p in all_files:
        pl = p.lower()
        if pl.endswith(".lab"):
            buckets["lab"].append(p)     # Common chord segment format
        elif "beat" in pl and (pl.endswith(".txt") or pl.endswith(".csv") or pl.endswith(".beats")):
            buckets["beats"].append(p)     # Beat times often stored as text
        elif pl.endswith(".json") and ("chord" in pl or "billboard" in pl):
            buckets["chords_json"].append(p)   # Some packs store chord segments as JSON
        elif pl.endswith(".csv") and ("index" in pl or "meta" in pl):
            buckets["metadata"].append(p)    # Metadata index files

    return buckets

# ----------------------------
# Reading chord segments + beats
# ----------------------------
@dataclass
class ChordSegment:
    start: float   # Segment start time (sec)
    end: float    # Segment end time (sec)
    label: str      # Chord label string

def read_lab_segments(lab_path: str) -> List[ChordSegment]:
    """
    Reads a .lab file with lines: <start> <end> <label>
    """
    segs: List[ChordSegment] = []    # Output list
    with open(lab_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < 3:
                continue     # Skip malformed lines
            start = float(parts[0])  # Parse start time
            end = float(parts[1])      # Parse end time
            label = " ".join(parts[2:])    # Join remaining as label
            segs.append(ChordSegment(start, end, label))    # Store segment
    return segs

def read_beat_times(path: str) -> Optional[np.ndarray]:
    """
    Attempts to read beat times as a 1D array of floats (seconds).
    Accepts simple formats: one beat time per line, or CSV with first column as time.
    """
    try:
        raw = []   # Collect beat times
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                # Take first token; works for "time" or "time,beatnum" formats
                token = re.split(r"[,\s]+", line)[0]
                raw.append(float(token))  # Parse float time
        arr = np.array(raw, dtype=float)
        arr = np.unique(arr)
        arr = np.sort(arr)
        if arr.size < 2:
            return None  # Not enough beats
        return arr
    except Exception:
        return None

# ----------------------------
# Discretize segments to beat-level labels
# ----------------------------
def label_at_time(segments: List[ChordSegment], t: float) -> str:
    """
    Finds chord label active at time t using segment boundaries.
    Assumes segments cover the song; if not, returns 'N'.
    """
    # Linear scan is fine for small lists; can optimize with pointers later
    for seg in segments:
        if seg.start <= t < seg.end:   # Check interval membership
            return seg.label    # Return segment label
    return "N"  # Default if no segment matches

def discretize_to_beats(segments: List[ChordSegment], beats: np.ndarray) -> List[int]:
    """
    Converts chord segments -> one chord label per beat interval.
    We assign chord based on the chord active at the beat time.
    """
    y_ids: List[int] = []  # Output class IDs
    for bt in beats[:-1]:     # Ignore last beat boundary
        lab = label_at_time(segments, float(bt))    # Get chord at beat time
        y_ids.append(chord_to_25class(lab))     # Map to 25-class ID
    return y_ids

def discretize_fixed_grid(segments: List[ChordSegment], hop_sec: float = 0.5) -> List[int]:
    """
    Fallback if beat times are unavailable: sample at a fixed time grid.
    """
    if not segments:
        return []
    t0 = segments[0].start     # Start time
    t1 = max(seg.end for seg in segments)   # End time
    times = np.arange(t0, t1, hop_sec, dtype=float)   # Uniform grid
    y_ids: List[int] = []  # Output class IDs
    for t in times:
        lab = label_at_time(segments, float(t))     # Get chord label at time
        y_ids.append(chord_to_25class(lab))   # Map to class ID
    return y_ids

# ----------------------------
# Corruption (noise) functions
# ----------------------------
def corrupt_uniform(y: List[int], eps: float, num_classes: int = 25) -> List[int]:
    """
    Uniform flip noise: with prob eps, replace with a random other label.
    """
    y = list(y)
    out = []
    for v in y:
        if np.random.rand() < eps:
            # Sample a different label than v
            cand = np.random.randint(0, num_classes)          # Propose random label
            while cand == v:
                cand = np.random.randint(0, num_classes)      # Resample if same
            out.append(int(cand))   # Add flipped label
        else:
            out.append(int(v))   # Keep original
    return out

def corrupt_burst(y: List[int], eps: float, burst_len_range: Tuple[int, int] = (2, 8),
                  num_classes: int = 25) -> List[int]:
    """
    Burst noise: flip contiguous spans until ~eps fraction of positions are corrupted.
    """
    y = list(y)
    n = len(y)
    target = int(np.ceil(eps * n))    # Target corrupted count
    out = y[:]
    corrupted = np.zeros(n, dtype=bool)    # Track corrupted positions

    while corrupted.sum() < target and n > 0:
        L = np.random.randint(burst_len_range[0], burst_len_range[1] + 1)  # Burst length
        start = np.random.randint(0, n)    # Burst start index
        end = min(n, start + L)       # Burst end index

        for i in range(start, end):
            if corrupted.sum() >= target:
                break      # Stop if target reached
            if corrupted[i]:
                continue      # Skip if already corrupted
            v = out[i]
            cand = np.random.randint(0, num_classes)      # Propose new label
            while cand == v:
                cand = np.random.randint(0, num_classes)      # Ensure different label
            out[i] = int(cand)   # Apply corruption
            corrupted[i] = True    # Mark corrupted

    return out

def corrupt(y: List[int], noise_type: str, eps: float) -> List[int]:
    """
    Wrapper for corruption methods.
    noise_type: 'uniform' or 'burst'
    """
    if noise_type == "uniform":
        return corrupt_uniform(y, eps)                        # Uniform flip
    if noise_type == "burst":
        return corrupt_burst(y, eps)                          # Burst noise
    raise ValueError(f"Unknown noise_type: {noise_type}")

# ----------------------------
# Build dataset: discover songs, create sequences
# ----------------------------
@dataclass
class SongExample:
    song_id: str   # Unique identifier
    y: List[int]    # Clean beat-level labels

def make_song_id_from_path(p: str) -> str:
    # Use a stable ID from relative path
    return re.sub(r"[^a-zA-Z0-9]+", "_", os.path.splitext(os.path.basename(p))[0])  # Simple ID

def build_sequences_from_kaggle_path(dataset_dir: str,
                                    prefer_beats: bool = True,
                                    fixed_hop_sec: float = 0.5,
                                    max_songs: Optional[int] = None) -> List[SongExample]:
    """
    Tries to build clean sequences for each song from .lab chord segments plus beat times if present.
    If beat files aren't found, falls back to fixed-grid sampling.
    """
    buckets = find_annotation_files(dataset_dir)    # Find candidate files
    lab_files = sorted(buckets["lab"])   # Sort lab files
    beat_files = sorted(buckets["beats"])   # Sort beat files

    # Make a quick lookup for beat files by basename
    beat_map: Dict[str, str] = {}
    for bf in beat_files:
        key = os.path.splitext(os.path.basename(bf))[0].lower()  # Base key
        beat_map[key] = bf   # Store path

    examples: List[SongExample] = []  # Output list
    for lab_path in lab_files:
        segs = read_lab_segments(lab_path)   # Read chord segments
        if not segs:
            continue
        base_key = os.path.splitext(os.path.basename(lab_path))[0].lower()  # Base key
        beats = None

        if prefer_beats and base_key in beat_map:
            beats = read_beat_times(beat_map[base_key])   # Read beats if matched

        if beats is not None:
            y_ids = discretize_to_beats(segs, beats)   # Beat-level labels
        else:
            y_ids = discretize_fixed_grid(segs, hop_sec=fixed_hop_sec)  # Fallback
        if len(y_ids) < 8:
            continue       # Skip too-short sequences

        song_id = make_song_id_from_path(lab_path)     # Create song ID
        examples.append(SongExample(song_id=song_id, y=y_ids))    # Store example

        if max_songs is not None and len(examples) >= max_songs:
            break

    return examples

# ----------------------------
# Train/val/test split (by song)
# ----------------------------
def split_by_song(examples: List[SongExample],
                  train_frac: float = 0.8,
                  val_frac: float = 0.1) -> Tuple[List[SongExample], List[SongExample], List[SongExample]]:
    """
    Splits examples by song (no leakage across splits).
    """
    ex = examples[:]
    random.shuffle(ex)   # Shuffle songs
    n = len(ex)
    n_train = int(train_frac * n)    # Train size
    n_val = int(val_frac * n)   # Val size
    train = ex[:n_train]       # Train slice
    val = ex[n_train:n_train + n_val]    # Val slice
    test = ex[n_train + n_val:]        # Test slice
    return train, val, test

set_seed(42)
# Build clean sequences
examples = build_sequences_from_kaggle_path(
    dataset_dir=DATASET_DIR,    # Kaggle dataset root
    prefer_beats=True,     # Try beat-level first
    fixed_hop_sec=0.5,     # Fallback resolution
    max_songs=None
)

print("Num songs parsed:", len(examples))   # Show number of sequences
print("Example lengths (first 5):", [len(e.y) for e in examples[:5]])

# Split into train/val/test by song
train_ex, val_ex, test_ex = split_by_song(examples, train_frac=0.8, val_frac=0.1)
print("Split sizes:", len(train_ex), len(val_ex), len(test_ex))

# Sanity check corruption on one example
eps = 0.20     # Example noise level
noise_type = "uniform"     # 'uniform' or 'burst'
y0 = train_ex[0].y     # Clean labels
x0 = corrupt(y0, noise_type=noise_type, eps=eps)    # Noisy labels

print("First 30 clean:", y0[:30])
print("First 30 noisy:", x0[:30])

"""## No Denoise Baseline"""

# Trivial baseline + evaluation + smoothness
# - Baseline: y_hat = x (no denoising)
# - Metrics:
#     (1) Accuracy vs clean y
#     (2) Smoothness / jitter: number of label changes per step
# - Evaluate across eps and noise types

# ----------------------------
# Metrics
# ----------------------------
def accuracy_seq(y_true: list[int], y_pred: list[int]) -> float:
    """
    Per-time-step accuracy for one sequence.
    """
    if len(y_true) == 0:
        return float("nan")
    yt = np.array(y_true, dtype=int)   # True labels array
    yp = np.array(y_pred, dtype=int)   # Pred labels array
    return float((yt == yp).mean())   # Fraction correct

def change_rate_seq(y_seq: list[int]) -> float:
    """
    Smoothness/jitter metric: fraction of adjacent steps that change.
    - 0.0 means perfectly constant
    - higher means more jitter / more frequent changes
    """
    if len(y_seq) < 2:
        return 0.0       # No adjacent pairs
    y = np.array(y_seq, dtype=int)
    changes = (y[1:] != y[:-1]).sum()  # Count changes
    return float(changes / (len(y_seq) - 1))  # Normalize by length

def evaluate_no_denoise(examples: list,
                        eps: float,
                        noise_type: str) -> dict:
    """
    Applies corruption to each song, predicts y_hat=x, returns mean metrics across songs.
    """
    accs = []     # Per-song accuracies
    change_rates = []    # Per-song change rates (jitter)

    for ex in examples:
        y = ex.y      # Clean sequence
        x = corrupt(y, noise_type=noise_type, eps=eps)      # Noisy observation
        y_hat = x       # No-denoise baseline output

        accs.append(accuracy_seq(y, y_hat))       # Accuracy vs clean
        change_rates.append(change_rate_seq(y_hat))    # Jitter of predicted sequence

    return {
        "acc_mean": float(np.nanmean(accs)),  # Mean accuracy
        "acc_std": float(np.nanstd(accs)),   # Std dev (optional)
        "change_mean": float(np.nanmean(change_rates)),   # Mean change rate
        "change_std": float(np.nanstd(change_rates)),   # Std dev (optional)
        "num_songs": int(len(examples)),    # Count
    }

# ----------------------------
# Run baseline across noise levels
# ----------------------------
set_seed(42)
noise_levels = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]
noise_types = ["uniform", "burst"]
# Use val while iterating; use test for final numbers
EVAL_SPLIT = test_ex
results = []        # Store rows for plotting

for nt in noise_types:
    for eps in noise_levels:
        metrics = evaluate_no_denoise(EVAL_SPLIT, eps=eps, noise_type=nt)  # Compute metrics
        results.append((nt, eps, metrics))    # Save result row
        print(
            f"[No-denoise] noise={nt:7s} eps={eps:.2f}  "
            f"acc={metrics['acc_mean']:.4f}  "
            f"change={metrics['change_mean']:.4f}  "
            f"(songs={metrics['num_songs']})"
        )

# Compact summary per noise type
print("\nAccuracy summary (eps:acc):")
for nt in noise_types:
    row = [(eps, m["acc_mean"]) for ntype, eps, m in results if ntype == nt]
    print(nt, "->", ", ".join([f"{eps:.2f}:{acc:.3f}" for eps, acc in row]))

print("\nSmoothness summary (eps:change_rate):")
for nt in noise_types:
    row = [(eps, m["change_mean"]) for ntype, eps, m in results if ntype == nt]
    print(nt, "->", ", ".join([f"{eps:.2f}:{cr:.3f}" for eps, cr in row]))

"""## HMM + Viterbi Baseline"""

# HMM baseline + Viterbi (MAP) + Forward-Backward (marginals) + evaluation
# - Learns transition matrix A from TRAIN clean sequences (counts + smoothing)
# - Uses emission/noise matrix B based on the corruption rate eps (uniform flip model)
# - Runs:
#     (1) Viterbi decode (MAP sequence)
#     (2) Forward-Backward marginals (sum-product BP on chain) + per-time argmax decode
# - Evaluates accuracy + smoothness + (for marginals) confidence

# ----------------------------
# Transition matrix estimate: A[j|i] = P(y_t=j | y_{t-1}=i)
# ----------------------------
def estimate_transition_matrix(examples: list, num_states: int = 25, alpha: float = 1.0) -> np.ndarray:
    """
    Estimate a first-order transition matrix from clean sequences using add-alpha smoothing.
    """
    counts = np.zeros((num_states, num_states), dtype=np.float64)     # How many times transition i to j occurs
    for ex in examples:
        y = ex.y      # Clean label sequence for this example
        if len(y) < 2:
            continue
        for t in range(len(y) - 1):  # Count each adjacent pair y[t] -> y[t+1]
            a = int(y[t])    # Previous state
            b = int(y[t + 1])   # Next state
            if 0 <= a < num_states and 0 <= b < num_states:
                counts[a, b] += 1.0   # Count valid states
    counts += alpha        # Add smoothing
    row_sums = counts.sum(axis=1, keepdims=True)     # Normalize rows
    A = counts / np.clip(row_sums, 1e-12, None)
    return A

# ----------------------------
# Emission matrix for uniform-flip corruption: B[y, x] = P(x | y)
# ----------------------------
def emission_uniform(num_states: int, eps: float) -> np.ndarray:
    """
    Uniform flip noise model:
      P(x=y) = 1-eps
      P(x!=y) = eps/(K-1)
    Returns B with shape (K,K) where B[y, x] = P(x | y).
    """
    K = num_states
    B = np.full((K, K), eps / max(K - 1, 1), dtype=np.float64)   # Off-diagonals corruption prob
    np.fill_diagonal(B, 1.0 - eps)   # Diagonal = prob of keeping correct label
    return B

# ----------------------------
# Viterbi decoding (MAP) in log-space
# ----------------------------
def viterbi_decode(x: list[int], A: np.ndarray, B: np.ndarray, pi: np.ndarray) -> list[int]:
    """
    Viterbi algorithm:
      x: observed labels (ints 0..K-1)
      A: transition probs (KxK), A[prev, cur]
      B: emission probs (KxK), B[y, x] = P(x|y)
      pi: initial distribution (K,)
    Returns:
      y_hat: MAP hidden state sequence (ints)
    """
    K = A.shape[0]   # Number of states
    T = len(x)
    if T == 0:
        return []
    # Convert probs into log probs
    logA = np.log(np.clip(A, 1e-300, None))
    logB = np.log(np.clip(B, 1e-300, None))
    logpi = np.log(np.clip(pi, 1e-300, None))
    # Best log score of any path ending in state y at time t and best prev state that led to y at t
    dp = np.full((T, K), -np.inf, dtype=np.float64)
    back = np.zeros((T, K), dtype=np.int32)
    # Initialization
    x0 = int(x[0])
    dp[0, :] = logpi + logB[:, x0]

    # Dynamic programming forward pass
    for t in range(1, T):
        xt = int(x[t])
        for y in range(K): # Best incoming path for each current hidden state y
            scores = dp[t - 1, :] + logA[:, y]  # Score of coming into y from every prev state
            best_prev = int(np.argmax(scores))
            dp[t, y] = scores[best_prev] + logB[y, xt]  # Best total score
            back[t, y] = best_prev

    # Backtrack
    yT = int(np.argmax(dp[T - 1, :]))
    # Output sequence
    y_hat = [0] * T
    y_hat[T - 1] = yT
    for t in range(T - 2, -1, -1):  # Follow backpointers from end to start
        y_hat[t] = int(back[t + 1, y_hat[t + 1]])

    return y_hat

# ----------------------------
# Forward-Backward marginals (sum-product BP on chain) with scaling
# ----------------------------
def forward_backward_marginals(x: list[int], A: np.ndarray, B: np.ndarray, pi: np.ndarray) -> np.ndarray:
    """
    Returns gamma[t,y] = P(y_t=y | x) using forward-backward with per-step scaling.
    """
    K = A.shape[0]
    T = len(x)
    if T == 0:  # Empty sequence
        return np.zeros((0, K), dtype=np.float64)
    # Scaled forward message up to time t and scaling factor at t
    alpha = np.zeros((T, K), dtype=np.float64)
    c = np.zeros(T, dtype=np.float64)
    # Init forward
    alpha[0, :] = pi * B[:, int(x[0])]
    c[0] = alpha[0, :].sum()
    alpha[0, :] /= max(c[0], 1e-12)

    # Rorward pass
    for t in range(1, T):
        xt = int(x[t])
        alpha[t, :] = (alpha[t - 1, :] @ A) * B[:, xt]  # Predict next state distribution and apply emission likelhood
        c[t] = alpha[t, :].sum()
        alpha[t, :] /= max(c[t], 1e-12)  # Normalize using scaling factor
    # Scaled backward message from future observations
    beta = np.zeros((T, K), dtype=np.float64)
    beta[T - 1, :] = 1.0

    # Backward pass
    for t in range(T - 2, -1, -1):
        xt1 = int(x[t + 1])  # Observation at next time step
        beta[t, :] = (A * (B[:, xt1] * beta[t + 1, :])[None, :]).sum(axis=1)
        beta[t, :] /= max(c[t + 1], 1e-12)  # Scaled message

    gamma = alpha * beta
    gamma /= np.clip(gamma.sum(axis=1, keepdims=True), 1e-12, None)
    return gamma

def decode_from_marginals(gamma: np.ndarray) -> list[int]:
    """
    Per-time-step decode from marginals: y_hat[t] = argmax_y gamma[t,y].
    (This is NOT the same as Viterbi MAP sequence.)
    """
    if gamma.shape[0] == 0:
        return []
    return [int(np.argmax(gamma[t])) for t in range(gamma.shape[0])]

# ----------------------------
# Evaluate Viterbi + Marginals
# ----------------------------
def evaluate_hmm_viterbi(examples: list, A: np.ndarray, eps: float, noise_type: str, num_states: int = 25) -> dict:
    """
    Evaluate HMM MAP decode (Viterbi).
    """
    pi = np.full(num_states, 1.0 / num_states, dtype=np.float64)  # Uniform prior over initial state
    B = emission_uniform(num_states, eps)   # Emission model from corruption level

    accs, changes = [], []
    for ex in examples:
        y = ex.y   # Clean sequence
        x = corrupt(y, noise_type=noise_type, eps=eps)  # Noisy observed sequence
        y_hat = viterbi_decode(x, A=A, B=B, pi=pi)  # Best hidden sequence recovered
        accs.append(accuracy_seq(y, y_hat))
        changes.append(change_rate_seq(y_hat))

    return {
        "acc_mean": float(np.mean(accs)),
        "acc_std": float(np.std(accs)),
        "change_mean": float(np.mean(changes)),
        "change_std": float(np.std(changes)),
        "num_songs": int(len(examples)),
    }

def evaluate_hmm_marginals(examples: list, A: np.ndarray, eps: float, noise_type: str, num_states: int = 25) -> dict:
    """
    Evaluate HMM marginals (forward-backward) + per-time argmax decode.
    Adds confidence = mean_t max_y gamma[t,y].
    """
    pi = np.full(num_states, 1.0 / num_states, dtype=np.float64)  # Uniform initial dist
    B = emission_uniform(num_states, eps)   # Emission model from corruption level

    accs, changes, confs = [], [], []
    for ex in examples:
        y = ex.y
        x = corrupt(y, noise_type=noise_type, eps=eps)
        gamma = forward_backward_marginals(x, A=A, B=B, pi=pi)  # Posterior marginals for each time/state
        y_hat = decode_from_marginals(gamma)   # Independent per-time-step decode

        accs.append(accuracy_seq(y, y_hat))
        changes.append(change_rate_seq(y_hat))
        confs.append(float(np.mean(np.max(gamma, axis=1))))

    return {
        "acc_mean": float(np.mean(accs)),
        "acc_std": float(np.std(accs)),
        "change_mean": float(np.mean(changes)),
        "change_std": float(np.std(changes)),
        "conf_mean": float(np.mean(confs)),
        "conf_std": float(np.std(confs)),
        "num_songs": int(len(examples)),
    }

# ----------------------------
# Run Step 4 on test/val set
# ----------------------------
A = estimate_transition_matrix(train_ex, num_states=25, alpha=1.0) # Learn transition matrix from clean training data
noise_levels = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]
noise_types = ["uniform", "burst"]

print("=== HMM + Viterbi (MAP) ===")
for nt in noise_types:
    for eps in noise_levels:  # Evaluate sequence-level MAP decoding
        m = evaluate_hmm_viterbi(EVAL_SPLIT, A=A, eps=eps, noise_type=nt, num_states=25)
        print(f"[HMM-Viterbi] noise={nt:7s} eps={eps:.2f}  acc={m['acc_mean']:.4f}  change={m['change_mean']:.4f}")

print("\n=== HMM + Forward-Backward (Marginals) ===")
for nt in noise_types:
    for eps in noise_levels:    # Evaluate per-time-step marginal decoding
        m = evaluate_hmm_marginals(EVAL_SPLIT, A=A, eps=eps, noise_type=nt, num_states=25)
        print(f"[HMM-Marginal] noise={nt:7s} eps={eps:.2f}  acc={m['acc_mean']:.4f}  change={m['change_mean']:.4f}  conf={m['conf_mean']:.4f}")

# Show one example decode for inspection
ex0 = EVAL_SPLIT[0]
eps0 = 0.20
nt0 = "uniform"
pi0 = np.full(25, 1.0 / 25, dtype=np.float64)
B0 = emission_uniform(25, eps0)
x0 = corrupt(ex0.y, noise_type=nt0, eps=eps0)

y_vit = viterbi_decode(x0, A=A, B=B0, pi=pi0)
gamma0 = forward_backward_marginals(x0, A=A, B=B0, pi=pi0)
y_mar = decode_from_marginals(gamma0)

print("\nExample check (first 40):")
print("clean:    ", ex0.y[:40])
print("noisy:    ", x0[:40])
print("viterbi:  ", y_vit[:40])
print("marginal: ", y_mar[:40])
print("conf(mean):", float(np.mean(np.max(gamma0, axis=1))))

"""## Heuristic Denoise Baselines"""

# Simple smoothing heuristic baselines (fast)
# - Adds 2 cheap denoisers that use only local consistency (no learning, no probabilities):
#     (A) Spike removal: replace single-point spikes (A B A -> A A A)
#     (B) Majority filter: sliding window majority vote (odd window size)
# - Evaluates accuracy + smoothness vs clean labels under uniform + burst noise

# ----------------------------
# Heuristic denoisers
# ----------------------------
def denoise_spike_removal(x: list[int]) -> list[int]:
    """
    Replace isolated spikes:
      if x[t-1] == x[t+1] and x[t] != x[t-1], set x[t] = x[t-1]
    This targets jitter like: 7,19,7  -> 7,7,7
    """
    if len(x) < 3:
        return list(x)    # Too short to smooth
    y = list(x)
    for t in range(1, len(x) - 1):
        left = x[t - 1]   # Left neighbor
        mid = x[t]    # Current
        right = x[t + 1]    # Right neighbor
        if left == right and mid != left:
            y[t] = left    # Remove spike
    return y

def denoise_majority_filter(x: list[int], window: int = 5) -> list[int]:
    """
    Sliding-window majority vote.
    - window must be odd
    - ties break by keeping original x[t]
    """
    if window < 3:
        return list(x)   # No smoothing
    if window % 2 == 0:
        raise ValueError("window must be odd")   # Guard even window

    n = len(x)
    r = window // 2  # Radius
    y = list(x)

    for t in range(n):
        lo = max(0, t - r)  # Window start
        hi = min(n, t + r + 1)     # Window end (exclusive)
        window_vals = x[lo:hi]    # Window slice
        counts = Counter(window_vals)  # Count labels
        best_label, best_count = counts.most_common(1)[0]  # Top label
        # Tie handling: if there is a tie for best_count, keep x[t]
        tied = [lab for lab, cnt in counts.items() if cnt == best_count]
        y[t] = x[t] if len(tied) > 1 else best_label
    return y

# ----------------------------
# Evaluation wrapper
# ----------------------------
def evaluate_heuristic(examples: list,
                       eps: float,
                       noise_type: str,
                       method: str,
                       window: int = 5) -> dict:
    """
    Corrupt clean y to get x, denoise x with chosen heuristic, then evaluate vs y.
    method: 'none', 'spike', 'majority'
    """
    accs = []
    changes = []

    for ex in examples:
        y = ex.y   # Clean labels
        x = corrupt(y, noise_type=noise_type, eps=eps)   # Noisy labels

        if method == "none":
            y_hat = x     # No denoise baseline
        elif method == "spike":
            y_hat = denoise_spike_removal(x)  # Spike removal
        elif method == "majority":
            y_hat = denoise_majority_filter(x, window=window)   # Majority filter
        else:
            raise ValueError(f"Unknown method: {method}")

        accs.append(accuracy_seq(y, y_hat)) # Accuracy vs clean
        changes.append(change_rate_seq(y_hat))    # Smoothness

    return {
        "acc_mean": float(np.mean(accs)),
        "acc_std": float(np.std(accs)),
        "change_mean": float(np.mean(changes)),
        "change_std": float(np.std(changes)),
        "num_songs": int(len(examples)),
    }

# ----------------------------
# Run on test/validation set
# ----------------------------
noise_levels = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]
noise_types = ["uniform", "burst"]
methods = [
    ("none", None),  # Baseline
    ("spike", None),   # A-B-A spike removal
    ("majority", 5),   # Majority window=5
]

print("=== Step 5: Heuristic denoisers ===")
for nt in noise_types:
    for eps in noise_levels:
        line_parts = [f"noise={nt:7s} eps={eps:.2f}"]
        for mname, win in methods:
            met = evaluate_heuristic(EVAL_SPLIT, eps=eps, noise_type=nt, method=mname, window=(win or 5))
            line_parts.append(f"{mname}: acc={met['acc_mean']:.4f}, chg={met['change_mean']:.4f}")
        print("  |  ".join(line_parts))

# Inspect one example for intuition
ex0 = EVAL_SPLIT[0]
eps0 = 0.20
nt0 = "uniform"
x0 = corrupt(ex0.y, noise_type=nt0, eps=eps0)

y_none = x0
y_spike = denoise_spike_removal(x0)
y_maj = denoise_majority_filter(x0, window=5)

print("\nExample check (first 40):")
print("clean:   ", ex0.y[:40])
print("noisy:   ", x0[:40])
print("none:    ", y_none[:40])
print("spike:   ", y_spike[:40])
print("major5:  ", y_maj[:40])

"""## GNN"""

# GNN with local-context features (x_{t-1}, x_t, x_{t+1})
# - Each node feature is a concatenation of embeddings of prev/current/next noisy labels
# - This gives the GNN more signal than just x_t alone
# ----------------------------
# Reproducibility
# ----------------------------
def set_torch_seed(seed: int = 42) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True      # Determinism
    torch.backends.cudnn.benchmark = False  # No autotune
set_torch_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")  # GPU if possible
print("Device:", device)
NUM_CLASSES = 25     # 25 chord classes
PAD_CLASS = NUM_CLASSES    # Extra token for boundaries (t=0, t=T-1)
VOCAB_SIZE = NUM_CLASSES + 1  # Include PAD token
NOISE_LEVELS = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]
NOISE_TYPES = ["uniform", "burst"]

# ----------------------------
# Chain graph edges
# ----------------------------
def chain_edge_index(T: int) -> torch.Tensor:
    if T < 2:
        return torch.empty((2, 0), dtype=torch.long)    # No edges
    src = torch.arange(0, T - 1, dtype=torch.long)   # 0..T-2
    dst = torch.arange(1, T, dtype=torch.long)   # 1..T-1
    e1 = torch.stack([src, dst], dim=0)    # Forward edges
    e2 = torch.stack([dst, src], dim=0)   # Backward edges
    return torch.cat([e1, e2], dim=1)  # Bidirectional chain

# ----------------------------
# Dataset: returns x_context (T x 3) and y (T)
# ----------------------------
class ChordChainDataset(torch.utils.data.Dataset):
    """
    Produces PyG graphs per song:
      - data.x_context: LongTensor [T, 3] with [x_prev, x_cur, x_next]
      - data.y:         LongTensor [T] clean labels
      - data.edge_index: chain edges
    """
    def __init__(self, examples, noise_levels, noise_types, mode="train"):
        self.examples = examples    # SongExample list
        self.noise_levels = noise_levels   # eps list
        self.noise_types = noise_types # Noise type list
        self.mode = mode     # train/eval mode

    def __len__(self) -> int:
        return len(self.examples)  # Number of songs

    def __getitem__(self, idx: int) -> Data:
        ex = self.examples[idx]  # Pick song
        y = ex.y    # Clean labels
        T = len(y)

        eps = random.choice(self.noise_levels) if self.mode == "train" else self.noise_levels[0]
        ntype = random.choice(self.noise_types) if self.mode == "train" else self.noise_types[0]
        x = corrupt(y, noise_type=ntype, eps=eps)              # Noisy labels
        # Build prev/cur/next context with PAD at boundaries
        x_prev = [PAD_CLASS] + x[:-1]        # Shift right
        x_cur  = x[:]      # Current
        x_next = x[1:] + [PAD_CLASS]          # Shift left

        x_context = torch.tensor(list(zip(x_prev, x_cur, x_next)), dtype=torch.long)  # [T,3]
        y_tensor = torch.tensor(y, dtype=torch.long)           # [T]

        edge_index = chain_edge_index(T)  # Chain edges

        data = Data(x_context=x_context, y=y_tensor, edge_index=edge_index)
        data.num_nodes = T
        data.seq_len = T
        data.eps = float(eps)
        data.ntype = str(ntype)
        return data

# ----------------------------
# Model: embed prev/cur/next separately (shared embedding), concat -> GraphSAGE -> logits
# ----------------------------
class GNNChordDenoiser(nn.Module):
    """
    Input: x_context [N,3] ints
    - Embed each column -> [N, embed_dim]
    - Concat -> [N, 3*embed_dim]
    - GraphSAGE layers -> [N, hidden_dim]
    - Linear -> [N, NUM_CLASSES]
    """
    def __init__(self, vocab_size: int, num_classes: int = 25, embed_dim: int = 64,
                 hidden_dim: int = 128, num_layers: int = 2, dropout: float = 0.2):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim)       # Includes PAD token
        in_dim = 3 * embed_dim      # Prev+cur+next concat
        self.convs = nn.ModuleList()  # Message passing layers
        self.convs.append(SAGEConv(in_dim, hidden_dim))         # First conv
        for _ in range(num_layers - 1):
            self.convs.append(SAGEConv(hidden_dim, hidden_dim)) # Deeper convs

        self.lin = nn.Linear(hidden_dim, num_classes)  # Classifier head
        self.dropout = dropout       # Dropout prob

    def forward(self, data: Data) -> torch.Tensor:
        xc = data.x_context     # [N,3]
        edge_index = data.edge_index   # Edges
        # Embed prev/cur/next and concatenate
        e_prev = self.embed(xc[:, 0])  # [N, D]
        e_cur  = self.embed(xc[:, 1])  # [N, D]
        e_next = self.embed(xc[:, 2])  # [N, D]
        h = torch.cat([e_prev, e_cur, e_next], dim=-1)  # [N, 3D]
        # Message passing
        for conv in self.convs:
            h = conv(h, edge_index)  # Aggregate neighbors
            h = F.relu(h)       # Nonlinearity
            h = F.dropout(h, p=self.dropout, training=self.training)  # Regularize
        logits = self.lin(h)   # [N, C]
        return logits

# ----------------------------
# Train/eval helpers (same idea as before)
# ----------------------------
def train_one_epoch(model, loader, optimizer) -> float:
    model.train()
    losses = []
    for batch in loader:  # Iterate each batch
        batch = batch.to(device)
        logits = model(batch)   # Forward pass
        loss = F.cross_entropy(logits, batch.y)  # CE loss
        optimizer.zero_grad()
        loss.backward()  # Backprop
        optimizer.step()
        losses.append(float(loss.item()))
    return float(np.mean(losses)) if losses else float("nan")

@torch.no_grad()
def evaluate_fixed_noise(model, examples, eps: float, noise_type: str, batch_size: int = 8):
    model.eval()
    ds = ChordChainDataset(examples, noise_levels=[eps], noise_types=[noise_type], mode="eval")
    loader = DataLoader(ds, batch_size=batch_size, shuffle=False)

    accs, changes = [], []
    for batch in loader:  # Iterate each batch
        batch = batch.to(device)
        logits = model(batch)   # Forward pass
        pred = logits.argmax(dim=-1).cpu().numpy()   # Calculate predictions
        ptr = batch.ptr.cpu().numpy()
        y_true = batch.y.cpu().numpy()

        for i in range(len(ptr) - 1):  # Calculate stats for each batch
            a, b = int(ptr[i]), int(ptr[i + 1])
            yt = y_true[a:b].tolist()  # True labels
            yp = pred[a:b].tolist()  # Predicted labels
            accs.append(accuracy_seq(yt, yp))
            changes.append(change_rate_seq(yp))

    return {"acc": float(np.mean(accs)), "change": float(np.mean(changes)), "num_songs": len(accs)}

# ----------------------------
# Train + eval grid
# ----------------------------
train_ds = ChordChainDataset(train_ex, noise_levels=NOISE_LEVELS, noise_types=NOISE_TYPES, mode="train")
train_loader = DataLoader(train_ds, batch_size=8, shuffle=True)
model = GNNChordDenoiser(vocab_size=VOCAB_SIZE, num_classes=NUM_CLASSES,
                         embed_dim=64, hidden_dim=128, num_layers=2, dropout=0.2).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
EPOCHS = 10
for epoch in range(1, EPOCHS + 1):
    tr_loss = train_one_epoch(model, train_loader, optimizer)
    print(f"Epoch {epoch:02d} | train_loss={tr_loss:.4f}")

print("\n=== GNN (context) evaluation on test ===")
for nt in NOISE_TYPES:
    for eps in NOISE_LEVELS:
        m = evaluate_fixed_noise(model, test_ex, eps=eps, noise_type=nt, batch_size=8)
        print(f"GNN noise={nt:7s} eps={eps:.2f}  acc={m['acc']:.4f}  change={m['change']:.4f}  (songs={m['num_songs']})")

# Generalization experiments for the GNN denoiser
# Goal: train on one noise type (uniform or burst) and test on both.
#
# Assumes you already have from Step 6:
#   - train_ex, val_ex, test_ex
#   - corrupt(y, noise_type, eps)
#   - accuracy_seq(y_true, y_pred), change_rate_seq(y_seq)
#   - ChordChainDataset (context version or x-only version) and GNNChordDenoiser
#   - evaluate_fixed_noise(model, examples, eps, noise_type, batch_size)

# ----------------------------
# Train helper
# ----------------------------
def train_model_for_noise(model, train_examples, noise_levels, train_noise_types,
                          epochs=10, batch_size=8, lr=1e-3, weight_decay=1e-4):
    """
    Train a model on a specified set of noise types (e.g., ['uniform'] or ['burst']).
    Returns trained model.
    """
    model = model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)

    train_ds = ChordChainDataset(
        examples=train_examples,
        noise_levels=noise_levels,
        noise_types=train_noise_types,
        mode="train"
    )
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)

    for ep in range(1, epochs + 1):
        model.train()
        losses = []
        for batch in train_loader:
            batch = batch.to(device)
            logits = model(batch)
            loss = F.cross_entropy(logits, batch.y)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            losses.append(float(loss.item()))
        print(f"Epoch {ep:02d} | train_loss={np.mean(losses):.4f}")

    return model

# ----------------------------
# Evaluation grid helper
# ----------------------------
def eval_grid(model, split_examples, noise_levels, noise_types, tag=""):
    """
    Print accuracy + smoothness for a grid of eps x noise_type.
    """
    print(f"\n=== Generalization Eval Grid {tag} ===")
    for nt in noise_types:
        for eps in noise_levels:
            m = evaluate_fixed_noise(model, split_examples, eps=eps, noise_type=nt, batch_size=8)
            print(f"{tag} [test] noise={nt:7s} eps={eps:.2f}  acc={m['acc']:.4f}  change={m['change']:.4f}")

# ----------------------------
# Run experiments
# ----------------------------
ALL_NOISE_TYPES = ["uniform", "burst"]

# Train on uniform only
model_u = GNNChordDenoiser(
    vocab_size=VOCAB_SIZE,   # If context model; remove if x-only model
    num_classes=NUM_CLASSES,
    embed_dim=64,
    hidden_dim=128,
    num_layers=2,
    dropout=0.2
)
print("\n### Training GNN-U (train on UNIFORM only)")
model_u = train_model_for_noise(
    model=model_u,
    train_examples=train_ex,
    noise_levels=NOISE_LEVELS,
    train_noise_types=["uniform"],
    epochs=10
)

# Evaluate on both uniform and burst
eval_grid(model_u, test_ex, NOISE_LEVELS, ALL_NOISE_TYPES, tag="GNN-U")

# (B) Train on burst only
model_b = GNNChordDenoiser(
    vocab_size=VOCAB_SIZE,
    num_classes=NUM_CLASSES,
    embed_dim=64,
    hidden_dim=128,
    num_layers=2,
    dropout=0.2
)
print("\n### Training GNN-B (train on BURST only)")
model_b = train_model_for_noise(
    model=model_b,
    train_examples=train_ex,
    noise_levels=NOISE_LEVELS,
    train_noise_types=["burst"],
    epochs=10
)

# Evaluate on both uniform and burst
eval_grid(model_b, test_ex, NOISE_LEVELS, ALL_NOISE_TYPES, tag="GNN-B")

# (C) Train on both (your current robust model)
model_mix = GNNChordDenoiser(
    vocab_size=VOCAB_SIZE,
    num_classes=NUM_CLASSES,
    embed_dim=64,
    hidden_dim=128,
    num_layers=2,
    dropout=0.2
)
print("\n### Training GNN-MIX (train on UNIFORM + BURST)")
model_mix = train_model_for_noise(
    model=model_mix,
    train_examples=train_ex,
    noise_levels=NOISE_LEVELS,
    train_noise_types=["uniform", "burst"],
    epochs=10
)

# Evaluate on both
eval_grid(model_mix, test_ex, NOISE_LEVELS, ALL_NOISE_TYPES, tag="GNN-MIX")

"""## Evaluation and Results"""

# Test cell to make sure dataset distribution of chords is normal
PITCHES = ["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]

def id_to_label(cid: int) -> str:
    if cid == 24:
        return "N"
    root = PITCHES[cid % 12]
    qual = "maj" if cid < 12 else "min"
    return f"{root}:{qual}"

def chord_distribution(examples, num_classes=25):
    c = Counter()
    total = 0
    for ex in examples:
        c.update(ex.y)
        total += len(ex.y)
    freqs = [(k, c[k], c[k]/total) for k in range(num_classes)]
    freqs.sort(key=lambda x: x[1], reverse=True)
    return freqs, total

# Choose which split(s) you want
freqs_train, total_train = chord_distribution(train_ex)
freqs_val, total_val = chord_distribution(val_ex)
freqs_test, total_test = chord_distribution(test_ex)

print("Total labels (train/val/test):", total_train, total_val, total_test)

top_k = 25
labels = [id_to_label(cid) for cid,_,_ in freqs_train[:top_k]]
vals = [frac for _,_,frac in freqs_train[:top_k]]

plt.figure()
plt.bar(range(top_k), vals)
plt.xticks(range(top_k), labels, rotation=45, ha="right")
plt.ylabel("Fraction of labels")
plt.title(f"Top {top_k} chord classes")
plt.tight_layout()
plt.show()

print("\nFull 25-class distribution (train):")
for cid, cnt, frac in sorted(freqs_train, key=lambda x: x[0]):
    print(f"{cid:2d}  {id_to_label(cid):6s}  count={cnt:8d}  frac={frac:.4f}")
uniq_counts = [len(set(ex.y)) for ex in train_ex]
print("Unique chord classes per song (train):")
print("min/median/max =", np.min(uniq_counts), np.median(uniq_counts), np.max(uniq_counts))

# ============================================================
# FINAL TEST / VAL COMPARISON
# Compares all main methods on the SAME corrupted split
# Methods:
#   - no-denoise
#   - spike heuristic
#   - majority heuristic
#   - HMM-Viterbi
#   - HMM-Marginal
#   - GNN-U
#   - GNN-B
#   - GNN-MIX
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

# ----------------------------
# Choose split here
# ----------------------------
SPLIT_NAME = "test"                 # change to "val" if needed
FINAL_SPLIT = test_ex               # change to val_ex if needed

FINAL_NOISE_LEVELS = NOISE_LEVELS[:]
FINAL_NOISE_TYPES = ["uniform", "burst"]
FINAL_SEED = 123

# ----------------------------
# Learn HMM transitions from TRAIN clean sequences
# ----------------------------
A_final = estimate_transition_matrix(
    train_ex,
    num_states=NUM_CLASSES,
    alpha=1.0
)

pi_final = np.full(NUM_CLASSES, 1.0 / NUM_CLASSES, dtype=np.float64)

# ----------------------------
# GNN prediction helper
# ----------------------------
@torch.no_grad()
def gnn_predict_from_noisy_sequence(model, x_seq):
    """Run one trained GNN on one already-corrupted sequence."""
    model.eval()

    T = len(x_seq)
    if T == 0:
        return []

    x_prev = [PAD_CLASS] + x_seq[:-1]
    x_cur  = x_seq[:]
    x_next = x_seq[1:] + [PAD_CLASS]

    x_context = torch.tensor(
        list(zip(x_prev, x_cur, x_next)),
        dtype=torch.long
    )

    data = Data(
        x_context=x_context,
        edge_index=chain_edge_index(T)
    )
    data.num_nodes = T
    data = data.to(device)

    logits = model(data)
    y_hat = logits.argmax(dim=-1).cpu().tolist()
    return y_hat

# ----------------------------
# Evaluate all methods on same corrupted sequences
# ----------------------------
def evaluate_all_methods_same_noise(
    examples,
    eps,
    noise_type,
    hmm_A,
    gnn_u_model,
    gnn_b_model,
    gnn_mix_model,
    majority_window=5
):
    """
    Corrupt each song ONCE, then evaluate every method on that same x.
    """
    B = emission_uniform(NUM_CLASSES, eps)

    metrics = {
        "none": [],
        "spike": [],
        "majority": [],
        "hmm_viterbi": [],
        "hmm_marginal": [],
        "gnn_u": [],
        "gnn_b": [],
        "gnn_mix": [],
    }

    for ex in examples:
        y = ex.y
        x = corrupt(y, noise_type=noise_type, eps=eps)

        # Baselines
        y_none = x
        y_spike = denoise_spike_removal(x)
        y_majority = denoise_majority_filter(x, window=majority_window)

        # HMM methods
        y_hmm_vit = viterbi_decode(
            x,
            A=hmm_A,
            B=B,
            pi=pi_final
        )

        gamma = forward_backward_marginals(
            x,
            A=hmm_A,
            B=B,
            pi=pi_final
        )
        y_hmm_mar = decode_from_marginals(gamma)

        # GNN methods
        y_gnn_u = gnn_predict_from_noisy_sequence(gnn_u_model, x)
        y_gnn_b = gnn_predict_from_noisy_sequence(gnn_b_model, x)
        y_gnn_mix = gnn_predict_from_noisy_sequence(gnn_mix_model, x)

        pred_dict = {
            "none": y_none,
            "spike": y_spike,
            "majority": y_majority,
            "hmm_viterbi": y_hmm_vit,
            "hmm_marginal": y_hmm_mar,
            "gnn_u": y_gnn_u,
            "gnn_b": y_gnn_b,
            "gnn_mix": y_gnn_mix,
        }

        for method_name, y_hat in pred_dict.items():
            metrics[method_name].append({
                "acc": accuracy_seq(y, y_hat),
                "change": change_rate_seq(y_hat),
            })

    rows = []
    for method_name, vals in metrics.items():
        accs = [v["acc"] for v in vals]
        chgs = [v["change"] for v in vals]

        rows.append({
            "noise_type": noise_type,
            "eps": eps,
            "method": method_name,
            "acc_mean": float(np.mean(accs)),
            "acc_std": float(np.std(accs)),
            "change_mean": float(np.mean(chgs)),
            "change_std": float(np.std(chgs)),
            "num_songs": len(vals),
        })

    return rows

# ----------------------------
# Run final sweep
# ----------------------------
set_seed(FINAL_SEED)
set_torch_seed(FINAL_SEED)

all_rows = []

for nt in FINAL_NOISE_TYPES:
    for eps in FINAL_NOISE_LEVELS:
        rows = evaluate_all_methods_same_noise(
            examples=FINAL_SPLIT,
            eps=eps,
            noise_type=nt,
            hmm_A=A_final,
            gnn_u_model=model_u,         # your trained uniform model
            gnn_b_model=model_b,         # your trained burst model
            gnn_mix_model=model_mix,     # your trained mixed model
            majority_window=5
        )
        all_rows.extend(rows)

df_final = pd.DataFrame(all_rows)

method_order = [
    "none",
    "spike",
    "majority",
    "hmm_viterbi",
    "hmm_marginal",
    "gnn_u",
    "gnn_b",
    "gnn_mix",
]

df_final["method"] = pd.Categorical(
    df_final["method"],
    categories=method_order,
    ordered=True
)

df_final = df_final.sort_values(
    ["noise_type", "eps", "method"]
).reset_index(drop=True)

print(f"=== Full final {SPLIT_NAME} results ===")
display(df_final)

# ----------------------------
# Summary tables
# ----------------------------
summary_acc = df_final.pivot_table(
    index=["noise_type", "eps"],
    columns="method",
    values="acc_mean"
)

summary_change = df_final.pivot_table(
    index=["noise_type", "eps"],
    columns="method",
    values="change_mean"
)

print("\n=== Accuracy summary table ===")
display(summary_acc)

print("\n=== Change-rate summary table ===")
display(summary_change)

# ----------------------------
# Accuracy plots
# ----------------------------
for nt in FINAL_NOISE_TYPES:
    plt.figure(figsize=(9, 5))

    df_nt = df_final[df_final["noise_type"] == nt]

    for method_name in method_order:
        df_m = df_nt[df_nt["method"] == method_name]
        plt.plot(
            df_m["eps"],
            df_m["acc_mean"],
            marker="o",
            label=method_name
        )

    plt.xlabel("Noise level (eps)")
    plt.ylabel(f"{SPLIT_NAME.capitalize()} accuracy")
    plt.title(f"Final {SPLIT_NAME}-set comparison | noise={nt}")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.show()

# ----------------------------
# Save csv
# ----------------------------
df_final.to_csv(f"final_comparison_{SPLIT_NAME}.csv", index=False)
print(f"\nSaved: final_comparison_{SPLIT_NAME}.csv")

# ============================================================
# QUALITATIVE EXAMPLES
# Shows:
#   clean, noisy, spike, majority, HMM-Viterbi, HMM-Marginal,
#   GNN-U, GNN-B, GNN-MIX
# ============================================================

def labels_to_text(seq):
    """Convert integer labels to chord names."""
    # Fix: Use the existing id_to_label function defined in cell oW2Puoe-NKMD
    return [id_to_label(int(x)) for x in seq]

def pretty_join(seq, max_len=None):
    """Compact display string."""
    if max_len is not None:
        seq = seq[:max_len]
    return " | ".join(seq)

def snippet_acc(y_true, y_pred):
    """Accuracy over one displayed snippet."""
    return sum(int(a == b) for a, b in zip(y_true, y_pred)) / max(1, len(y_true))

def show_example_predictions(
    examples,
    example_indices=(0, 1, 2),
    eps=0.30,
    noise_type="uniform",
    start=0,
    window=24,
    majority_window=5
):
    """
    Show qualitative predictions for selected songs on same noisy input.
    """
    B = emission_uniform(NUM_CLASSES, eps)

    for ex_id in example_indices:
        ex = examples[ex_id]
        y = ex.y
        x = corrupt(y, noise_type=noise_type, eps=eps)

        # Main methods
        y_none = x
        y_spike = denoise_spike_removal(x)
        y_maj = denoise_majority_filter(x, window=majority_window)

        y_vit = viterbi_decode(
            x,
            A=A_final,
            B=B,
            pi=pi_final
        )

        gamma = forward_backward_marginals(
            x,
            A=A_final,
            B=B,
            pi=pi_final
        )
        y_mar = decode_from_marginals(gamma)

        y_gnn_u = gnn_predict_from_noisy_sequence(model_u, x)
        y_gnn_b = gnn_predict_from_noisy_sequence(model_b, x)
        y_gnn_mix = gnn_predict_from_noisy_sequence(model_mix, x)

        # Slice snippet
        s = start
        e = min(start + window, len(y))

        clean_txt = labels_to_text(y[s:e])
        noisy_txt = labels_to_text(y_none[s:e])
        spike_txt = labels_to_text(y_spike[s:e])
        maj_txt   = labels_to_text(y_maj[s:e])
        vit_txt   = labels_to_text(y_vit[s:e])
        mar_txt   = labels_to_text(y_mar[s:e])
        gnn_u_txt = labels_to_text(y_gnn_u[s:e])
        gnn_b_txt = labels_to_text(y_gnn_b[s:e])
        gnn_mix_txt = labels_to_text(y_gnn_mix[s:e])

        print("=" * 110)
        print(f"Example index: {ex_id} | noise_type={noise_type} | eps={eps} | span=[{s}:{e}]")
        print("-" * 110)
        print("Clean        :", pretty_join(clean_txt))
        print("Noisy        :", pretty_join(noisy_txt))
        print("Spike        :", pretty_join(spike_txt))
        print("Majority     :", pretty_join(maj_txt))
        print("HMM-Viterbi  :", pretty_join(vit_txt))
        print("HMM-Marginal :", pretty_join(mar_txt))
        print("GNN-U        :", pretty_join(gnn_u_txt))
        print("GNN-B        :", pretty_join(gnn_b_txt))
        print("GNN-MIX      :", pretty_join(gnn_mix_txt))
        print()

        print("Snippet accuracies")
        print(f"  Noisy        : {snippet_acc(y[s:e], y_none[s:e]):.3f}")
        print(f"  Spike        : {snippet_acc(y[s:e], y_spike[s:e]):.3f}")
        print(f"  Majority     : {snippet_acc(y[s:e], y_maj[s:e]):.3f}")
        print(f"  HMM-Viterbi  : {snippet_acc(y[s:e], y_vit[s:e]):.3f}")
        print(f"  HMM-Marginal : {snippet_acc(y[s:e], y_mar[s:e]):.3f}")
        print(f"  GNN-U        : {snippet_acc(y[s:e], y_gnn_u[s:e]):.3f}")
        print(f"  GNN-B        : {snippet_acc(y[s:e], y_gnn_b[s:e]):.3f}")
        print(f"  GNN-MIX      : {snippet_acc(y[s:e], y_gnn_mix[s:e]):.3f}")
        print()

# Example usage
show_example_predictions(
    examples=test_ex,
    example_indices=(0, 3, 7),
    eps=0.30,
    noise_type="uniform",
    start=0,
    window=20
)

# ============================================================
# FINAL PACKAGING SETUP
# Creates one output folder for all final report / slide assets
# ============================================================

from pathlib import Path                         # Path handling
import pandas as pd                             # Tables
import numpy as np                              # Numeric helpers
import matplotlib.pyplot as plt                 # Plotting
import time                                     # Runtime timing
import textwrap                                 # Text formatting

# Output folder for final assets
FINAL_DIR = Path("final_assets")                # Folder name
FINAL_DIR.mkdir(exist_ok=True)                  # Create if missing

# Load results if df_final is not already in memory
if "df_final" not in globals():                 # Only load if needed
    csv_candidates = [                          # Possible file names
        "final_comparison_test.csv",
        "final_test_comparison.csv",
        "final_comparison_test (1).csv"
    ]
    loaded = False                              # Track whether load succeeded
    for csv_name in csv_candidates:             # Try each candidate
        csv_path = Path(csv_name)               # Build path
        if csv_path.exists():                   # Check file exists
            df_final = pd.read_csv(csv_path)    # Load csv
            loaded = True                       # Mark success
            print(f"Loaded results from {csv_name}")
            break
    if not loaded:                              # If nothing found
        raise FileNotFoundError("Could not find a final comparison CSV or df_final in memory.")

# Clean method ordering for tables and plots
METHOD_ORDER = [
    "none",
    "spike",
    "majority",
    "hmm_viterbi",
    "hmm_marginal",
    "gnn_u",
    "gnn_b",
    "gnn_mix",
]

LABEL_MAP = {                                   # Nicer names for figures/tables
    "none": "No denoise",
    "spike": "Spike removal",
    "majority": "Majority filter",
    "hmm_viterbi": "HMM Viterbi",
    "hmm_marginal": "HMM Marginal",
    "gnn_u": "GNN-U",
    "gnn_b": "GNN-B",
    "gnn_mix": "GNN-MIX",
}

df_final["method"] = pd.Categorical(            # Enforce clean order
    df_final["method"],
    categories=METHOD_ORDER,
    ordered=True
)

df_final = df_final.sort_values(                # Sort once globally
    ["noise_type", "eps", "method"]
).reset_index(drop=True)

print(f"Final assets will be saved in: {FINAL_DIR.resolve()}")
display(df_final.head())

# ============================================================
# FINAL SUMMARY TABLES
# Saves full and compact accuracy/change-rate tables
# ============================================================

# Full accuracy pivot table
acc_table = df_final.pivot_table(               # Accuracy summary
    index=["noise_type", "eps"],
    columns="method",
    values="acc_mean"
)

# Full change-rate pivot table
chg_table = df_final.pivot_table(               # Change-rate summary
    index=["noise_type", "eps"],
    columns="method",
    values="change_mean"
)

# Rename columns for readability
acc_table = acc_table.rename(columns=LABEL_MAP) # Better display names
chg_table = chg_table.rename(columns=LABEL_MAP) # Better display names

# Save full tables
acc_table.to_csv(FINAL_DIR / "accuracy_summary_full.csv")       # Full accuracy
chg_table.to_csv(FINAL_DIR / "change_rate_summary_full.csv")    # Full change rate

# Compact table for report/slides
EPS_KEEP = [0.10, 0.30, 0.50]                  # Main eps values to highlight
compact_df = df_final[df_final["eps"].isin(EPS_KEEP)].copy()    # Keep only key rows

compact_acc = compact_df.pivot_table(          # Compact accuracy table
    index=["noise_type", "eps"],
    columns="method",
    values="acc_mean"
).rename(columns=LABEL_MAP)

compact_chg = compact_df.pivot_table(          # Compact change-rate table
    index=["noise_type", "eps"],
    columns="method",
    values="change_mean"
).rename(columns=LABEL_MAP)

compact_acc.to_csv(FINAL_DIR / "accuracy_summary_compact.csv")  # Save compact accuracy
compact_chg.to_csv(FINAL_DIR / "change_rate_summary_compact.csv")  # Save compact change

print("Saved summary tables:")
print(" - accuracy_summary_full.csv")
print(" - change_rate_summary_full.csv")
print(" - accuracy_summary_compact.csv")
print(" - change_rate_summary_compact.csv")

print("\n=== Compact accuracy table ===")
display(compact_acc)

print("\n=== Compact change-rate table ===")
display(compact_chg)

# ============================================================
# FINAL ACCURACY FIGURES
# Creates clean PNGs for uniform and burst noise
# ============================================================

for noise_type in ["uniform", "burst"]:        # Make one plot per noise type
    plt.figure(figsize=(8.5, 5.5))             # One figure only

    df_nt = df_final[df_final["noise_type"] == noise_type]  # Filter noise type

    for method_name in METHOD_ORDER:           # Plot methods in fixed order
        df_m = df_nt[df_nt["method"] == method_name]        # Method subset
        plt.plot(
            df_m["eps"],                       # X = noise level
            df_m["acc_mean"],                  # Y = accuracy
            marker="o",                        # Points
            linewidth=2,                       # Thicker lines
            label=LABEL_MAP[method_name]       # Pretty legend text
        )

    plt.xlabel("Noise level (epsilon)")        # X label
    plt.ylabel("Test accuracy")                # Y label
    plt.title(f"Chord denoising accuracy under {noise_type} noise")  # Title
    plt.grid(True)                             # Grid
    plt.legend()                               # Legend
    plt.tight_layout()                         # Clean layout

    out_path = FINAL_DIR / f"accuracy_{noise_type}.png"  # Save name
    plt.savefig(out_path, dpi=300, bbox_inches="tight")  # Save figure
    plt.show()                                 # Display in notebook

    print(f"Saved: {out_path.name}")

# ============================================================
# FINAL CHANGE-RATE FIGURES
# Creates clean PNGs for uniform and burst noise
# ============================================================

for noise_type in ["uniform", "burst"]:        # Make one plot per noise type
    plt.figure(figsize=(8.5, 5.5))             # One figure only

    df_nt = df_final[df_final["noise_type"] == noise_type]  # Filter noise type

    for method_name in METHOD_ORDER:           # Plot methods in fixed order
        df_m = df_nt[df_nt["method"] == method_name]        # Method subset
        plt.plot(
            df_m["eps"],                       # X = noise level
            df_m["change_mean"],               # Y = change rate
            marker="o",                        # Points
            linewidth=2,                       # Thicker lines
            label=LABEL_MAP[method_name]       # Pretty legend text
        )

    plt.xlabel("Noise level (epsilon)")        # X label
    plt.ylabel("Change rate")                  # Y label
    plt.title(f"Change rate under {noise_type} noise")      # Title
    plt.grid(True)                             # Grid
    plt.legend()                               # Legend
    plt.tight_layout()                         # Clean layout

    out_path = FINAL_DIR / f"change_rate_{noise_type}.png"  # Save name
    plt.savefig(out_path, dpi=300, bbox_inches="tight")     # Save figure
    plt.show()                                 # Display in notebook

    print(f"Saved: {out_path.name}")

# ============================================================
# QUALITATIVE EXAMPLES
# Finds informative snippets and saves them to a text file
# ============================================================

def labels_to_text(seq):                        # Int labels -> chord names
    return [id_to_label(int(x)) for x in seq]

def snippet_acc(y_true, y_pred):                # Accuracy on snippet
    return sum(int(a == b) for a, b in zip(y_true, y_pred)) / max(1, len(y_true))

def pretty_join(seq):                           # Compact readable text
    return " | ".join(seq)

def method_predictions_for_sequence(y, x, B):   # Run all methods on one corrupted seq
    y_none = x                                  # No denoise baseline
    y_spike = denoise_spike_removal(x)          # Spike heuristic
    y_maj = denoise_majority_filter(x, window=5)  # Majority filter

    y_vit = viterbi_decode(                     # HMM Viterbi
        x,
        A=A_final,
        B=B,
        pi=pi_final
    )

    gamma = forward_backward_marginals(         # HMM marginals
        x,
        A=A_final,
        B=B,
        pi=pi_final
    )
    y_mar = decode_from_marginals(gamma)        # Decode marginals

    y_u = gnn_predict_from_noisy_sequence(model_u, x)       # GNN-U
    y_b = gnn_predict_from_noisy_sequence(model_b, x)       # GNN-B
    y_mix = gnn_predict_from_noisy_sequence(model_mix, x)   # GNN-MIX

    return {                                    # Return dictionary
        "Noisy": y_none,
        "Spike": y_spike,
        "Majority": y_maj,
        "HMM-Viterbi": y_vit,
        "HMM-Marginal": y_mar,
        "GNN-U": y_u,
        "GNN-B": y_b,
        "GNN-MIX": y_mix,
    }

def find_good_examples(
    examples,
    noise_type="uniform",
    eps=0.30,
    window=20,
    max_examples=3,
    seed=123
):
    rng = np.random.default_rng(seed)          # Reproducible sampling
    B = emission_uniform(NUM_CLASSES, eps)     # HMM emission matrix
    candidates = []                            # Store candidate snippets

    example_order = list(range(len(examples))) # All song indices
    rng.shuffle(example_order)                 # Shuffle order

    for ex_id in example_order:                # Check each song
        y = examples[ex_id].y                  # Clean sequence
        if len(y) < window:                    # Skip very short songs
            continue

        x = corrupt(y, noise_type=noise_type, eps=eps)      # Corrupt once
        preds = method_predictions_for_sequence(y, x, B)    # Run all methods

        # Try all possible snippet starts
        for start in range(0, len(y) - window + 1):
            end = start + window               # End index

            noisy_acc = snippet_acc(y[start:end], preds["Noisy"][start:end])          # Noisy acc
            hmm_acc = snippet_acc(y[start:end], preds["HMM-Marginal"][start:end])     # HMM acc
            gnn_acc = snippet_acc(y[start:end], preds["GNN-MIX"][start:end])          # GNN acc

            # Score = how informative the snippet is
            score = (hmm_acc - noisy_acc) + (gnn_acc - noisy_acc)  # Combined improvement

            candidates.append({                # Save candidate
                "ex_id": ex_id,
                "start": start,
                "end": end,
                "score": score,
                "y": y,
                "x": x,
                "preds": preds,
            })

    # Sort by best informative score first
    candidates = sorted(candidates, key=lambda d: d["score"], reverse=True)

    # Keep unique songs only
    chosen = []                                # Selected examples
    used_song_ids = set()                      # Avoid repeats from same song
    for cand in candidates:                    # Scan sorted candidates
        if cand["ex_id"] in used_song_ids:     # Skip duplicate songs
            continue
        chosen.append(cand)                    # Keep this one
        used_song_ids.add(cand["ex_id"])       # Mark used
        if len(chosen) >= max_examples:        # Stop after enough examples
            break

    return chosen                              # Return chosen snippets

# Choose one uniform and one burst set
examples_uniform = find_good_examples(         # Uniform examples
    test_ex,
    noise_type="uniform",
    eps=0.30,
    window=20,
    max_examples=2,
    seed=123
)

examples_burst = find_good_examples(           # Burst examples
    test_ex,
    noise_type="burst",
    eps=0.30,
    window=20,
    max_examples=2,
    seed=456
)

# Save examples to text file
out_txt = FINAL_DIR / "qualitative_examples.txt"   # Output file

with open(out_txt, "w", encoding="utf-8") as f:    # Open output file
    for block_name, example_list in [("UNIFORM NOISE", examples_uniform), ("BURST NOISE", examples_burst)]:
        f.write("=" * 100 + "\n")                 # Section divider
        f.write(block_name + "\n")                # Section title
        f.write("=" * 100 + "\n\n")               # Divider

        for idx, item in enumerate(example_list, start=1):  # Enumerate selected examples
            s = item["start"]                     # Start index
            e = item["end"]                       # End index
            y = item["y"]                         # Clean sequence
            x = item["x"]                         # Corrupted sequence
            preds = item["preds"]                 # Predictions

            f.write(f"Example {idx} | song_index={item['ex_id']} | span=[{s}:{e}]\n")  # Header
            f.write("-" * 100 + "\n")             # Divider

            f.write("Clean        : " + pretty_join(labels_to_text(y[s:e])) + "\n")
            f.write("Noisy        : " + pretty_join(labels_to_text(x[s:e])) + "\n")
            f.write("Spike        : " + pretty_join(labels_to_text(preds["Spike"][s:e])) + "\n")
            f.write("Majority     : " + pretty_join(labels_to_text(preds["Majority"][s:e])) + "\n")
            f.write("HMM-Viterbi  : " + pretty_join(labels_to_text(preds["HMM-Viterbi"][s:e])) + "\n")
            f.write("HMM-Marginal : " + pretty_join(labels_to_text(preds["HMM-Marginal"][s:e])) + "\n")
            f.write("GNN-U        : " + pretty_join(labels_to_text(preds["GNN-U"][s:e])) + "\n")
            f.write("GNN-B        : " + pretty_join(labels_to_text(preds["GNN-B"][s:e])) + "\n")
            f.write("GNN-MIX      : " + pretty_join(labels_to_text(preds["GNN-MIX"][s:e])) + "\n\n")

            f.write("Snippet accuracies\n")      # Metric block
            for method_name in ["Noisy", "Spike", "Majority", "HMM-Viterbi", "HMM-Marginal", "GNN-U", "GNN-B", "GNN-MIX"]:
                acc_val = snippet_acc(y[s:e], preds[method_name][s:e] if method_name != "Noisy" else x[s:e])
                f.write(f"  {method_name:<12}: {acc_val:.3f}\n")
            f.write("\n\n")

print(f"Saved: {out_txt.name}")

# Also print them in notebook for quick review
print(out_txt.read_text(encoding="utf-8")[:6000])  # Print first chunk only

# ============================================================
# POLISHED REPORT TABLE
# Keeps only the most important methods for a clean final table
# ============================================================

BEST_METHODS = [                                # Methods most worth reporting
    "none",
    "hmm_viterbi",
    "hmm_marginal",
    "gnn_u",
    "gnn_b",
    "gnn_mix",
]

report_df = df_final[df_final["method"].isin(BEST_METHODS)].copy()  # Subset

report_table = report_df.pivot_table(           # Accuracy summary
    index=["noise_type", "eps"],
    columns="method",
    values="acc_mean"
).rename(columns=LABEL_MAP)

report_table.to_csv(FINAL_DIR / "report_accuracy_table.csv")        # Save table

print("=== Report accuracy table ===")
display(report_table.round(3))
print("Saved: report_accuracy_table.csv")

# ============================================================
# OPTIONAL RUNTIME COMPARISON
# Times HMM-Marginal, HMM-Viterbi, and GNN-MIX on a few test songs
# ============================================================

RUNTIME_N = min(10, len(test_ex))               # Number of songs to time
RUNTIME_EPS = 0.30                              # Moderate noise
RUNTIME_NOISE = "uniform"                       # Pick one noise type
B = emission_uniform(NUM_CLASSES, RUNTIME_EPS) # HMM emission

runtime_rows = []                               # Store runtime results

for i in range(RUNTIME_N):                      # Loop test songs
    y = test_ex[i].y                            # Clean sequence
    x = corrupt(y, noise_type=RUNTIME_NOISE, eps=RUNTIME_EPS)  # Corrupt sequence

    # Time HMM-Viterbi
    t0 = time.perf_counter()                    # Start timer
    _ = viterbi_decode(x, A=A_final, B=B, pi=pi_final)
    t1 = time.perf_counter()                    # Stop timer
    vit_time = t1 - t0                          # Elapsed

    # Time HMM-Marginal
    t0 = time.perf_counter()                    # Start timer
    gamma = forward_backward_marginals(x, A=A_final, B=B, pi=pi_final)
    _ = decode_from_marginals(gamma)
    t1 = time.perf_counter()                    # Stop timer
    mar_time = t1 - t0                          # Elapsed

    # Time GNN-MIX
    t0 = time.perf_counter()                    # Start timer
    _ = gnn_predict_from_noisy_sequence(model_mix, x)
    t1 = time.perf_counter()                    # Stop timer
    gnn_time = t1 - t0                          # Elapsed

    runtime_rows.append({                       # Save runtimes
        "song_index": i,
        "length": len(y),
        "hmm_viterbi_sec": vit_time,
        "hmm_marginal_sec": mar_time,
        "gnn_mix_sec": gnn_time,
    })

runtime_df = pd.DataFrame(runtime_rows)         # Build DataFrame
runtime_df.to_csv(FINAL_DIR / "runtime_table.csv", index=False)  # Save raw runtimes

runtime_summary = runtime_df[                   # Mean runtime summary
    ["hmm_viterbi_sec", "hmm_marginal_sec", "gnn_mix_sec"]
].mean().to_frame(name="mean_seconds")

runtime_summary.to_csv(FINAL_DIR / "runtime_summary.csv")         # Save summary

print("=== Runtime summary (seconds) ===")
display(runtime_summary)
print("Saved: runtime_table.csv and runtime_summary.csv")